M48
; DRILL file {KiCad 7.0.9} date Tue Mar 26 00:40:35 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-26T00:40:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
%
G90
G05
T1
X57.287Y-124.21
X57.287Y-129.99
X196.75Y-100.71
X196.75Y-106.49
T0
M30
